[theme]
primaryColor = "#3fb950"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#c9d1d9"
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "error"

[server]
maxUploadSize = 200
